version: '3.4'

services:
  ui:
    image: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ui:/app
    depends_on:
      - db
      - model
    restart: always
  db:
    image: postgres:12-bullseye
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=demo
    restart: always
  model:
    image: model
    build:
      context: .
      dockerfile: ./model/Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./model:/app
    environment:
      - TRANSFORMERS_CACHE=/app/.cache